version: "3"
services: 
    hello:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
        - 9000:9000
        volumes:
        - ~/Desktop/VscodeDebugGuideForPHP:/www
    nginx:
        image: nginx
        volumes:
        - ./nginx.conf:/etc/nginx/conf.d/server.conf:ro
        depends_on:
        - hello
        ports:
        - 8080:8080
